dotfiles_repo: "{{ ansible_env.HOME }}/.dotfiles"

git_user_name: "ArminIrannejad"
git_user_email: "armin.irannejad@gmail.com"

packages_common:
  - git
  - zsh
  - ripgrep
  - fzf
  - curl
  - wget
  - neovim
  - npm
  - nodejs
  - tmux
  - unzip
  - btop
  - build-essential
  - tmux

zsh_default_shell: true
neovim_enabled: true
starship_enabled: true
config_dir: "{{ ansible_env.HOME }}/.config"
bin_dir: "{{ ansible_env.HOME }}/bin"
